tasks:
  - name: Backend
    init: |
      # Install PostgreSQL client
      sudo apt-get update && sudo apt-get install -y postgresql-client
      # Create database (if needed)
      createdb -h localhost -U wizfi wisdom_api
      npm install
    command: npm run start

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore