image:
  file: .gitpod.Dockerfile

tasks:
  - name: Backend
    init: |
      # Install PostgreSQL client if not in Dockerfile
      sudo apt-get update && sudo apt-get install -y postgresql-client
      
      # Wait for PostgreSQL
      while ! pg_isready -h localhost -p 5432 -U wizfi; do sleep 1; done
      
      # Create database
      createdb -h localhost -U wizfi wisdom_api || true
      
      npm install
    command: npm run start

ports:
  - port: 3001
    onOpen: open-browser
    description: Node.js Application
  - port: 5432
    onOpen: ignore
    description: PostgreSQL Database
