image:
  file: Dockerfile

tasks:
  - name: Backend
    init: |
      # Quietly check for PostgreSQL
      while ! pg_isready -h localhost -p 5432 -U wizfi >/dev/null 2>&1; do sleep 1; done
      
      # Create database quietly
      createdb -h localhost -U wizfi wisdom_api >/dev/null 2>&1 || true
      
      # Install dependencies
      npm install --quiet
    command: npm run start

ports:
  - port: 3001
    onOpen: open-browser
    description: Node.js Application
  - port: 5432
    onOpen: ignore
    description: PostgreSQL Database