image:
  file: Dockerfile  # Uses your existing Dockerfile

tasks:
  - name: Backend
    init: |
      # Wait for PostgreSQL to be ready
      while ! pg_isready -h localhost -p 5432; do sleep 1; done
      # Create database if it doesn't exist
      createdb -h localhost -U wizfi wisdom_api || true
      npm install
    command: npm run start

ports:
  - port: 3001
    onOpen: open-browser
    description: Node.js Application
  - port: 5432
    onOpen: ignore
    description: PostgreSQL Database
