version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: wizfi
      POSTGRES_PASSWORD: Wisdomwise1
      POSTGRES_DB: wisdom_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wizfi -d wisdom_api"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - .:/workspace/Wisdom14DaysofCodeAndDesign
      - /workspace/Wisdom14DaysofCodeAndDesign/node_modules
    environment:
      DATABASE_URL: "postgres://wizfi:Wisdomwise1@postgres:5432/wisdom_api"
      DB_HOST: "wisdom14daysofcodeanddesign-postgres-1"
      DB_PORT: "5432"
      DB_USER: "wizfi"
      DB_PASSWORD: "Wisdomwise1"
      DB_NAME: "wisdom_api"
    stdin_open: true
    tty: true
    command: bash -c "while ! nc -z postgres 5432; do sleep 1; done && npm install && npm start"

volumes:
  postgres-data: