version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: wizfi
      POSTGRES_PASSWORD: Wisdomwise1
      POSTGRES_DB: wisdom_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: